# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ViabilidadGlamping
                                 A QGIS plugin
 Plugin para evaluar viabilidad de glampings
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-24
        copyright            : (C) 2026 by Maria Camila Rueda Cano
        email                : camilarueda715@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ViabilidadGlamping class from file ViabilidadGlamping.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Plugin import ViabilidadGlamping
    return ViabilidadGlamping(iface)
